version: '3.8'

services:
  dns:
    image: internetsystemsconsortium/bind9:9.19
    container_name: dns
    hostname: dns
    volumes:
      #- ./dns/named.conf.local:/data/named.conf.local
      - ./dns/db.asirloayza.net:/etc/bind/db.asirloayza.net
    networks:
      pfcNetwork:
        ipv4_address: 192.168.1.2
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  dhcp:
    image: joebiellik/dhcpd
    container_name: dhcp
    hostname: dhcp
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
    networks:
      pfcNetwork:
        ipv4_address: 192.168.1.3
    ports:
      - "67:67/udp"
    environment:
      - INTERFACES=eth0
    #  - RANGE=192.168.1.100,192.168.1.254
    #  - DNS=192.168.1.2
    #  - SUBNET=255.255.255.0
    #  - ROUTER=192.168.1.1

  apache:
    image: php:apache
    container_name: apache
    hostname: apache
    volumes:
      - ./web/apache/asirloayza.net.conf:/etc/apache2/sites-available/asirloayza.net.conf
      - ./web/www:/var/www/html
    networks:
      pfcNetwork:
        ipv4_address: 192.168.1.4
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    #command: bash -c "a2ensite asirloayza.net.conf && a2dissite 000-default.conf && service apache2 reload"
  
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      pfcNetwork:
        ipv4_address: 192.168.1.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pfcdlk
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  
networks:
  pfcNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  mysql-data: