# Utiliza una imagen base de PHP con Apache
FROM php:apache

# Instala el cliente MySQL
RUN apt-get update && docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Copia los archivos de configuración de Apache
COPY ./web/apache/asirloayza.net.conf /etc/apache2/sites-available/asirloayza.net.conf
COPY ./web/www /var/www/html

# Habilita los módulos necesarios de Apache
RUN a2enmod rewrite
RUN a2ensite asirloayza.net.conf
RUN a2dissite 000-default.conf

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Exponer el puerto 80 y 443 para que Apache pueda servir contenido web
EXPOSE 80
EXPOSE 443

# Ejecutar Apache en primer plano al iniciar el contenedor
CMD ["apache2-foreground"]